### ISSUE TITLE
zero crossing sketch

### ISSUE THREAD

**Issue by kikiloaw** [MartinStokroos/openMicroInverter#3]
ive been trying to simulate the sketch
first the inverter. working fine producing pulse. but in the schematic only the high side mosfet have pulse and the two lowside mosfet is always have 5v signal.  

then I tried the ZCD sketch,  I tried to put 2.5 volts at D6 as ref for comparator, then put some 2.5v sinewave in the D7 and analog 2 but to simulate the reading of the voltage of the grid. but theres the problem is that the output sinewave of the inverter is not syncing to the grid. 
in your  README.md it says: "The sign of the sine wave is determined from the ADC input". in my understand this is where the syncing of phase occur. but in my case it is not.
https://github.com/kikiloaw/openMicroInverter
heres the clone i made from yours
@MartinStokroos  thanks in advance

**Comment by MartinStokroos** [comment]
About the pulse: are BHI and AHI of U1 both connected to +5V? If pins 9 and 10 of the Arduino produce pulse, the full bridge should switch.

The ZCD sketch is only a demonstrator for a zcd comparator. There is no PWM output produced in this sketch, no syncing of the outputwave either. I use the sign of the input wave in the zcd to prevent from glitches. 
I already proved a synced output wave myself, but I need to make the sketch ready for publication. I hope I'll find some time soon. In the end I do not use my zcd for syncing. I use phase sensitive detection on the adc input.

My sketches are meant as thoughts to create all the building blocks that are needed to build a functional inverter with Arduino.

Thank you for your interest.

**Comment by kikiloaw** [comment]
Yes this project is very interesting, i found a grid tie in the net 3 years ago by tim nolan but it is not worth to try since components availability is through online and expensive that's why i am very excited when i see this repository. Components are available., and also i can make changes about the sensor since the library is open source also. It makes my job easier now.
