### ISSUE TITLE
hi martin

### ISSUE THREAD

**Issue by kikiloaw** [MartinStokroos/openMicroInverter#5]
I'm still looking forward for this project. I hope you make this compatible using acs712.Tthe LV 25-P AND LA 55-A is very expensive. maybe some alternative that I could use.

**Comment by MartinStokroos** [comment]
Hi Kikiloaw,

Thank you for your suggestion to use the ACS712 for this project. My first impression from the datasheet is, that this chip could do the work for the design. I will consider the use of this chip in the final hardware design. Thanks.

**Comment by kikiloaw** [comment]
hi martin thanks for considering about this one.. may you should consider other method also measuring the voltage? not only the current? thanks regards

**Comment by MartinStokroos** [comment]
Hi kikiloaw, voltage measurment will be implemented with low cost opamp solution.
