### ISSUE TITLE
pcb footprints 

### ISSUE THREAD

**Issue by pixelpoppul-zz** [MartinStokroos/openMicroInverter#6]
it would be awesome if you could include the PCB footprints for them. I would really like to upgrade it to a higher wattage system

kinda surprised that the internet only got openMicroinverter and an older outdated one called OSSI
I did add a voltage and wattage measurement on my board which is a mainboard and it's simple  maybe u could implement it in this ? I will upload their files soon If possible

**Comment by MartinStokroos** [comment]
Thanks for your interest. I am planning a pcb design when I have solved the difficulties in the software to a certain extent. Upgrading to higher power levels is something to be decided yourself. It is a matter of scaling the measured quantities.
The voltage and power measurements are already implemented but maybe not send out to via serial in all the examples.

**Comment by pixelpoppul-zz** [comment]
Can i know the current issues in the software?  I can disucss that with my buddies and possible figure that out 😁

**Comment by pixelpoppul-zz** [comment]
i noticed the voltage rating values for capacitors are missing. It would be great if that was available.  I want to replicate the dev board and test out some things so it would be great if you could list out those values

**Comment by MartinStokroos** [comment]
To pixelpoppul: most important issue with the software is that I want the 100% PWM range back to increase the efficiency of the inverter. Stepping back to a higher PWM frequency is almost impossible for keeping all the functionality it performs so far.

In the newer schematics I will notice the capacitor voltage ratings. It is not too complicated.
For all ceramic capacitors around the opamps, H-bridge driver and Arduino: 50V (X7R dielectric).
The Electrolytic capacitors across the DC-bus: overrate up to 20-30% of the applied DC voltage.
For the capacitors across the mains voltage: they should be qualified to connect with the ac mains voltage in your region. Use so called X-capacitors only.

**Comment by pixelpoppul-zz** [comment]
Tried SPWM?  Also do you have plans to do any major changes in the schematic as i almost done making a nice pcb for it so major changes would be a pain😅  thanks for the capacitor values!
