### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by hydro86** [MartinStokroos/openMicroInverter#7]
Hi Mr. Martin Stokroos,

I would like to felicitate you for the project and the involved content.
Question: do you have make tests on breadboards or is there an already routed PCB available for this project?
I only found the schematics.
I'm Engineer in electronics and also teacher and would like to contribute. So perhaps we can do a routing and add to the repo?
Also I would like to make a V2 with an ESP32.

Waiting your answer
Best regards

**Comment by MartinStokroos** [comment]
Hi hydro86,
Sorry for my very late reply. I appreciate your willingness to contribute.
With this project I am exploring out certain things with power electronics. I work with a breadboard minimal hardware setup. I am not completely satisfied about my software implementation yet. Maybe I will pick up the project again once. As long as some critical parts of the software are not solved, it is not worth it to put a lot of effort in the hardware design I think.
Anyway, thanks for your offer.
Best,
Martin
